blank_issues_enabled: false
contact_links:
  - name: Telegram Official Group
    url: https://t.me/buxxedchat
    about: Please ask and answer questions here.
  - name: Telegram Official Channel
    url: https://t.me/buxxed
    about: Our Official Telegram Channel